apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stateledger-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

commonAnnotations:
  environment: dev

patchesStrategicMerge:
  - deployment.yaml

replicas:
  - name: stateledger
    count: 1
