apiVersion: v1
kind: Service
metadata:
  name: stateledger
spec:
  type: ClusterIP
  selector:
    app: stateledger
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
