apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stateledger

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

commonAnnotations:
  environment: staging

patchesStrategicMerge:
  - deployment.yaml
  - pvc.yaml

replicas:
  - name: stateledger
    count: 2
